version: "3.9"

services:
  backend:
    build: .
    container_name: careerai-backend
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload


  # redis:
  #   image: redis/redis-stack:latest
  #   container_name: careerai-redis
  #   ports:
  #     - "6379:6379"
  #     - "8001:8001" # Redis stack UI

volumes:
  mongo_data:
