[project]
name = "careerai-backend"
version = "0.1.0"
description = "FastAPI backend for CareerAI"
requires-python = ">=3.12"

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "motor",
    "redis",
    "python-dotenv",
    "requests",
    "pydantic",
    "pydantic-settings",
    "sqlmodel",
    "passlib[bcrypt]",
    "pyjwt",
    "email-validator",
    "websockets",
    "orjson",
    "langchain",
    "langchain-openai",
    "langgraph",
    "langgraph-checkpoint-redis",
    "redisvl",
    "bcrypt<4.1",
]

[tool.uv]
dev-dependencies = [
    "pytest",
    "pip-check-reqs",
    "deptry>=0.23.1",
]
